[build]
builder = "NIXPACKS"
buildCommand = "pnpm --filter medapp-ui build"
watchPatterns = ["apps/ui/**"]

[deploy]
startCommand = "pnpm --filter medapp-ui start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
